version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sudoku
      - CLIENT_URL=http://localhost
      - CORS_ORIGINS=http://localhost
      - PORT=5000
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
volumes:
  mongo-data:
